naming:
    MatchingDeclarationName:
        active: false
    MemberNameEqualsClassName:
        active: false
    FunctionNaming:
        ignoreAnnotated: ['Composable']
    TopLevelPropertyNaming:
        constantPattern: '[A-Z][A-Za-z0-9]*'
complexity:
    LongParameterList:
        ignoreDefaultParameters: true
        functionThreshold: 10
    LongMethod:
        threshold: 80
    NestedBlockDepth:
        threshold: 5
style:
    excludes: ['**/*.kts']
    MagicNumber:
        active: false
    NewLineAtEndOfFile:
        active: false
    UnusedPrivateMember:
        ignoreAnnotated: ['Preview']

formatting:
    FinalNewline:
        active: false
    ImportOrdering:
        active: false