name: Detekt

on: [push, pull_request]

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup detekt
      id: setup_detekt
      run: |
        dest=$( mktemp -d )
        DETEKT_FILE=$dest/detekt-cli-all.jar
        curl --request GET \
          --url https://github.com/detekt/detekt/releases/download/v1.21.0/detekt-cli-1.21.0-all.jar \
          --silent \
          --location \
          --output $DETEKT_FILE
        echo "::set-output name=detekt_file::$DETEKT_FILE"

    - name: Run Detekt
      continue-on-error: false
      run: |
        java -jar ${{ steps.setup_detekt.outputs.detekt_file }} -c ${{ github.workspace }}/detekt_config.yml --build-upon-default-config  --input ${{ github.workspace }}